language: generic
cache: false
install: skip
services:
  - docker
git:
  clone: false
branches:
  only:
  - master
if: (commit_message =~ ^daily OR type = "cron") AND (branch = master)
env:
  - WEBGRAB_FILENAME=configs/fr_telerama.xml
  - WEBGRAB_FILENAME=configs/programme_tv.xml
  - WEBGRAB_FILENAME=configs/programme_tv2.xml
  - WEBGRAB_FILENAME=configs/programme_tv3.xml
  - WEBGRAB_FILENAME=configs/programme_tv4.xml
  - WEBGRAB_FILENAME=configs/fr_canal.xml
  - WEBGRAB_FILENAME=configs/fr_canal3.xml
before_script:
  - export TZ=Europe/London
script: |
  wget https://raw.githubusercontent.com/Fazzani/grab/master/build.sh -O build.sh
  chmod +x ./build.sh && ./build.sh --build

jobs:
  include:
  - stage: merging
    name: Merging xmltv files
    script: |
      wget https://raw.githubusercontent.com/Fazzani/grab/master/build.sh -O build.sh
      chmod +x build.sh
      ./build.sh --merge

notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
